# Generated by Django 4.1.5 on 2023-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_watchlist_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='init_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
