# Generated by Django 4.1.5 on 2023-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist_comments_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
